# Generated by Django 5.2.5 on 2025-08-30 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_profile_profile_pic_profile_address_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='request',
            old_name='latitude',
            new_name='location',
        ),
        migrations.RemoveField(
            model_name='request',
            name='longitude',
        ),
        migrations.AddField(
            model_name='request',
            name='garbage_type',
            field=models.TextField(blank=True, null=True),
        ),
    ]
