# Generated by Django 5.2.5 on 2025-08-31 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_rename_latitude_request_location_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='status',
            field=models.TextField(default='Pending'),
        ),
    ]
