# Generated by Django 5.2.7 on 2025-11-20 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_request_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='sacks',
            field=models.TextField(blank=True, null=True),
        ),
    ]
